#pragma once

#include <SDL3/SDL.h>

#include "IGameWorldRenderer.h"

// High-level representation of game data for rendering. Generated by GameWorld.
// Uses in SDL renderer and ImGui.
class GameWorldRenderer : public IGameWorldRenderer {
 public:
  void init(SDL_Renderer* renderer);
  void render();

 private:
  SDL_Renderer* renderer_ = nullptr;
};
