#pragma once

#include <glm/glm.hpp>
#include <string>
#include <vector>

// High-level representation of game data for rendering. Generated by GameWorld.
// Uses in SDL renderer and ImGui.
struct GameDataForRendering {
  std::vector<glm::vec2> points;
  mutable std::string latestMessageFromServer;
};
