#pragma once

#include <glm/glm.hpp>
#include <string>
#include <vector>

// High-level representation of data for rendering. Generated by ChatManager.
// Uses in SDL renderer to create ImGui.
struct DataForRendering {
  std::vector<std::string> chatHistory;
  bool isConnected = false;
};
